
login_check:
    path: /login_check
    methods: [POST]

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

register_client:
    path: /register
    controller: App\Controller\ClientController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\ClientController::api